<template>
  <button
    class="col-span-2 border border-blue-500 place-self-end self-center rounded hover:bg-blue-500 hover:text-white col-start-7 w-24 h-full flex justify-center items-center"
    :disabled="isFormSent"
  >
    <template v-if="isFormSent">
      <svg
        class="animate-spin"
        xmlns="http://www.w3.org/2000/svg"
        xmlns:xlink="http://www.w3.org/1999/xlink"
        width="21px"
        height="21px"
        viewBox="0 0 100 100"
        preserveAspectRatio="xMidYMid"
        style="
          margin-right: -2px;
          display: block;
          background-color: rgba(255, 255, 255, 0);
        "
      >
        <circle
          cx="50"
          cy="50"
          fill="none"
          stroke="#95B9EE"
          stroke-width="10"
          r="35"
          stroke-dasharray="164.93361431346415 56.97787143782138"
          transform="matrix(1,0,0,1,0,0)"
          style="transform: matrix(1, 0, 0, 1, 0, 0)"
        ></circle>
        <!-- generated by https://loading.io/ -->
      </svg>
    </template>
    <template v-else>
      <p>Создать</p>
    </template>
  </button>
</template>
<script setup>
defineProps({ isFormSent: { type: Boolean, required: true } })
</script>
